"""
Run XFeat SAR/OPT matching with ICRAFT compiled frontend models in soft simulation.

This follows the runtime quick-start soft simulation style:
  Network.CreateFromJsonFile(...)
  network.loadParamsFromFile(...)
  Session.Create([HostBackend], network.view(0), [HostDevice.Default()])
  session.forward([Tensor(input_nhwc, Layout("NHWC"))])

The frontend is deployed as two single-image compiled models:
  - xfeat_800 for optical 800x800 input
  - xfeat_512 for SAR 512x512 input

Host-side post-processing decodes sparse XFeat features, performs mutual-NN
descriptor matching, runs RANSAC and saves match visualizations.

The Python HostBackend path can run parsed/optimized/quantized/adapted stages
directly. The generated BY stage is also selectable, but the current xfeat_800
BY artifact may require ICRAFT's generated FTMP memory layout and can fail when
fed with a plain Python Tensor.
"""

from __future__ import annotations

import argparse
import csv
import math
import time
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn.functional as F

from icraft.xir import *  # noqa: F403
from icraft.xrt import *  # noqa: F403
from icraft.host_backend import *  # noqa: F403

from modules.interpolator import InterpolateSparse2d
from xfeat_sar_opt_eval import (
    LabelRow,
    affine_stats,
    corner_rmse,
    estimate_transform,
    find_image,
    make_gt_aug_to_opt,
    mutual_nn_matches,
    parse_float_list,
    preprocess_gray,
    read_gray,
    read_labels,
    selected_labels,
    synthetic_sar_view,
    transform_points,
)


REPO_DIR = Path(__file__).resolve().parent
DEFAULT_DATA_ROOT = Path(r"D:\HanZhQ\PCIE715\Project_Trans\2350")

STAGE_CHOICES = ("parsed", "optimized", "quantized", "adapted", "BY")
DEFAULT_STAGE = "optimized"


def default_model_paths(size: int, stage: str) -> tuple[Path, Path]:
    net_name = f"xfeat_frontend_{size}"
    model_dir = REPO_DIR / "icraft_compile" / f"xfeat_{size}" / "imodels" / net_name
    return model_dir / f"{net_name}_{stage}.json", model_dir / f"{net_name}_{stage}.raw"


@dataclass
class MatchResult:
    image_id: str
    stage: str
    angle_deg: float
    synthetic_scale: float
    matches: int
    inliers: int
    inlier_ratio: float
    accepted: bool
    corner_rmse: float
    tx: float
    ty: float
    estimated_scale: float
    estimated_angle_deg: float
    icraft_opt_s: float
    icraft_sar_s: float
    total_s: float
    matrix: np.ndarray | None
    inlier_mask: np.ndarray | None
    opt_pts: np.ndarray
    sar_pts: np.ndarray
    opt_img: np.ndarray
    sar_img: np.ndarray
    draw_path: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="XFeat ICRAFT soft-sim SAR/OPT matching.")
    parser.add_argument("mode", nargs="?", choices=["single", "batch"], default="single")
    parser.add_argument("--data-root", type=Path, default=DEFAULT_DATA_ROOT)
    parser.add_argument(
        "--stage",
        choices=STAGE_CHOICES,
        default=DEFAULT_STAGE,
        help="ICRAFT model stage used by Python HostBackend. BY is selectable, but xfeat_800 BY may need FTMP-layout input.",
    )
    parser.add_argument("--json-512", type=Path, default=None, help="Override SAR 512 model json.")
    parser.add_argument("--raw-512", type=Path, default=None, help="Override SAR 512 model raw.")
    parser.add_argument("--json-800", type=Path, default=None, help="Override optical 800 model json.")
    parser.add_argument("--raw-800", type=Path, default=None, help="Override optical 800 model raw.")
    parser.add_argument("--output-dir", type=Path, default=REPO_DIR / "outputs" / "xfeat_icraft_soft_sim_match")
    parser.add_argument("--image-id", default="100001", help="single mode image id.")
    parser.add_argument("--ids", nargs="*", default=None, help="batch mode explicit ids.")
    parser.add_argument("--limit", type=int, default=10, help="batch mode limit. 0 means all selected ids.")
    parser.add_argument("--top-k", type=int, default=3072)
    parser.add_argument("--detection-threshold", type=float, default=0.05)
    parser.add_argument("--min-cossim", type=float, default=-1.0)
    parser.add_argument("--ransac-thr", type=float, default=6.0)
    parser.add_argument("--model", choices=["similarity", "affine", "homography"], default="similarity")
    parser.add_argument("--preprocess", choices=["raw", "clahe", "grad", "canny"], default="grad")
    parser.add_argument("--sar-blur", type=int, default=3)
    parser.add_argument("--angles", default="0")
    parser.add_argument("--scales", default="1.0")
    parser.add_argument("--min-accept-inliers", type=int, default=30)
    parser.add_argument("--min-accept-ratio", type=float, default=0.04)
    parser.add_argument("--max-draw", type=int, default=250)
    parser.add_argument("--no-images", action="store_true")
    return parser.parse_args()


def require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(path)


def resolve_model_paths(size: int, stage: str, json_override: Path | None, raw_override: Path | None) -> tuple[Path, Path]:
    json_path, raw_path = default_model_paths(size, stage)
    if json_override is not None:
        json_path = json_override
    if raw_override is not None:
        raw_path = raw_override
    return json_path, raw_path


class IcraftSoftFrontend:
    def __init__(self, json_path: Path, raw_path: Path, height: int, width: int, name: str, stage: str):
        require_file(json_path)
        require_file(raw_path)
        self.height = height
        self.width = width
        self.name = name
        self.stage = stage
        network = Network.CreateFromJsonFile(str(json_path))
        network.loadParamsFromFile(str(raw_path))
        self.session = Session.Create([HostBackend], network.view(0), [HostDevice.Default()])
        self.session.apply()
        print(f"INFO: created soft-sim session {name} stage={stage}: {json_path}")

    def forward(self, image: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, float]:
        if image.shape[:2] != (self.height, self.width):
            image = cv2.resize(image, (self.width, self.height), interpolation=cv2.INTER_LINEAR)
        tensor_nhwc = image.astype(np.float32).reshape(1, self.height, self.width, 1)
        input_tensor = Tensor(tensor_nhwc, Layout("NHWC"))
        start = time.perf_counter()
        try:
            outputs = self.session.forward([input_tensor])
        except Exception as exc:
            if self.stage == "BY":
                raise RuntimeError(
                    f"{self.name} BY soft-sim failed with plain Tensor input. "
                    "Use --stage optimized/quantized/adapted for Python HostBackend, "
                    "or run the BY artifact through ICRAFT's generated FTMP flow."
                ) from exc
            raise
        elapsed = time.perf_counter() - start
        arrays = [np.array(output) for output in outputs]
        if len(arrays) < 3:
            raise RuntimeError(f"{self.name} expected 3 outputs, got {len(arrays)}")
        dense = normalize_output("dense_descriptors", arrays[0], self.height, self.width)
        logits = normalize_output("keypoint_logits", arrays[1], self.height, self.width)
        reliability = normalize_output("reliability", arrays[2], self.height, self.width)
        return dense, logits, reliability, elapsed


class IcraftSoftXFeat:
    def __init__(self, args: argparse.Namespace):
        self.stage = args.stage
        json_512, raw_512 = resolve_model_paths(512, args.stage, args.json_512, args.raw_512)
        json_800, raw_800 = resolve_model_paths(800, args.stage, args.json_800, args.raw_800)
        self.sar = IcraftSoftFrontend(json_512, raw_512, 512, 512, "xfeat_512", args.stage)
        self.opt = IcraftSoftFrontend(json_800, raw_800, 800, 800, "xfeat_800", args.stage)

    def detect_and_compute(
        self,
        image: np.ndarray,
        role: str,
        top_k: int,
        detection_threshold: float,
    ) -> tuple[dict[str, torch.Tensor], float]:
        frontend = self.opt if role == "opt" else self.sar
        dense, logits, reliability, elapsed = frontend.forward(image)
        features = decode_sparse_features(dense, logits, reliability, top_k, detection_threshold)
        return features, elapsed


def normalize_output(name: str, array: np.ndarray, height: int, width: int) -> np.ndarray:
    channels = {"dense_descriptors": 64, "keypoint_logits": 65, "reliability": 1}[name]
    out_h, out_w = height // 8, width // 8
    nchw_shape = (1, channels, out_h, out_w)
    nhwc_shape = (1, out_h, out_w, channels)
    # ICRAFT parsed/generated models are created with NHWC inputs and emit NHWC
    # outputs. For xfeat_512 dense descriptors, NHWC and NCHW are both
    # (1, 64, 64, 64), so prefer NHWC to avoid silently scrambling descriptors.
    if array.shape == nhwc_shape:
        return np.transpose(array, (0, 3, 1, 2)).astype(np.float32, copy=False)
    if array.shape == nchw_shape:
        return array.astype(np.float32, copy=False)
    raise ValueError(f"{name} shape {array.shape} does not match {nchw_shape} or {nhwc_shape}")


def get_kpts_heatmap(kpts: torch.Tensor, softmax_temp: float = 1.0) -> torch.Tensor:
    scores = F.softmax(kpts * softmax_temp, 1)[:, :64]
    batch, _, height, width = scores.shape
    heatmap = scores.permute(0, 2, 3, 1).reshape(batch, height, width, 8, 8)
    heatmap = heatmap.permute(0, 1, 3, 2, 4).reshape(batch, 1, height * 8, width * 8)
    return heatmap


def nms(heatmap: torch.Tensor, threshold: float, kernel_size: int = 5) -> torch.Tensor:
    batch, _, _, _ = heatmap.shape
    pad = kernel_size // 2
    local_max = torch.nn.MaxPool2d(kernel_size=kernel_size, stride=1, padding=pad)(heatmap)
    pos = (heatmap == local_max) & (heatmap > threshold)
    pos_batched = [item.nonzero()[..., 1:].flip(-1) for item in pos]
    pad_val = max([len(item) for item in pos_batched] + [1])
    points = torch.zeros((batch, pad_val, 2), dtype=torch.long, device=heatmap.device)
    for batch_idx, item in enumerate(pos_batched):
        points[batch_idx, : len(item), :] = item
    return points


@torch.inference_mode()
def decode_sparse_features(
    dense_descriptors: np.ndarray,
    keypoint_logits: np.ndarray,
    reliability: np.ndarray,
    top_k: int,
    detection_threshold: float,
) -> dict[str, torch.Tensor]:
    m1 = torch.from_numpy(dense_descriptors).float()
    k1 = torch.from_numpy(keypoint_logits).float()
    h1 = torch.from_numpy(reliability).float()

    m1 = F.normalize(m1, dim=1)
    k1h = get_kpts_heatmap(k1)
    mkpts = nms(k1h, threshold=detection_threshold, kernel_size=5)

    nearest = InterpolateSparse2d("nearest")
    bilinear = InterpolateSparse2d("bilinear")
    scores = (nearest(k1h, mkpts, k1h.shape[-2], k1h.shape[-1]) * bilinear(h1, mkpts, k1h.shape[-2], k1h.shape[-1])).squeeze(-1)
    scores[torch.all(mkpts == 0, dim=-1)] = -1

    idxs = torch.argsort(-scores)
    mkpts_x = torch.gather(mkpts[..., 0], -1, idxs)[:, :top_k]
    mkpts_y = torch.gather(mkpts[..., 1], -1, idxs)[:, :top_k]
    mkpts = torch.cat([mkpts_x[..., None], mkpts_y[..., None]], dim=-1)
    scores = torch.gather(scores, -1, idxs)[:, :top_k]

    descriptors = InterpolateSparse2d("bicubic")(m1, mkpts, H=k1h.shape[-2], W=k1h.shape[-1])
    descriptors = F.normalize(descriptors, dim=-1)

    valid = scores[0] > 0
    return {
        "keypoints": mkpts[0][valid].float(),
        "scores": scores[0][valid].float(),
        "descriptors": descriptors[0][valid].float(),
    }


def resolve_labels(args: argparse.Namespace) -> list[LabelRow]:
    labels = read_labels(args.data_root / "label.txt")
    if args.mode == "single":
        return selected_labels(labels, [args.image_id], 1)
    return selected_labels(labels, args.ids, args.limit)


def run_one_case(
    label: LabelRow,
    angle: float,
    scale: float,
    xfeat: IcraftSoftXFeat,
    args: argparse.Namespace,
) -> MatchResult:
    total_start = time.perf_counter()
    opt_raw = read_gray(find_image(args.data_root, "opt", label.image_id))
    sar_raw = read_gray(find_image(args.data_root, "sar", label.image_id))
    opt = preprocess_gray(opt_raw, args.preprocess, is_sar=False, sar_blur=args.sar_blur)
    sar_aug_raw, aug_to_src = synthetic_sar_view(sar_raw, angle, scale)
    sar = preprocess_gray(sar_aug_raw, args.preprocess, is_sar=True, sar_blur=args.sar_blur)
    gt_aug_to_opt = make_gt_aug_to_opt(label.x, label.y, aug_to_src)

    opt_feat, opt_s = xfeat.detect_and_compute(opt, "opt", args.top_k, args.detection_threshold)
    sar_feat, sar_s = xfeat.detect_and_compute(sar, "sar", args.top_k, args.detection_threshold)
    sar_idx, opt_idx, _scores = mutual_nn_matches(sar_feat["descriptors"], opt_feat["descriptors"], args.min_cossim)

    sar_pts = sar_feat["keypoints"][sar_idx].cpu().numpy().astype(np.float32)
    opt_pts = opt_feat["keypoints"][opt_idx].cpu().numpy().astype(np.float32)
    matrix, inliers = estimate_transform(sar_pts, opt_pts, args.model, args.ransac_thr)

    matches = int(len(sar_pts))
    inlier_count = int(inliers.sum()) if inliers is not None else 0
    inlier_ratio = (inlier_count / matches) if matches else 0.0
    accepted = inlier_count >= args.min_accept_inliers and inlier_ratio >= args.min_accept_ratio
    rmse = corner_rmse(matrix, sar.shape[1], sar.shape[0], gt_aug_to_opt)
    tx, ty, est_scale, est_angle = affine_stats(matrix)

    stem = f"{label.image_id}_a{angle:g}_s{scale:g}_{args.preprocess}_{args.model}.jpg"
    draw_path = "" if args.no_images else str(args.output_dir / "matches" / stem)
    result = MatchResult(
        image_id=label.image_id,
        stage=xfeat.stage,
        angle_deg=angle,
        synthetic_scale=scale,
        matches=matches,
        inliers=inlier_count,
        inlier_ratio=inlier_ratio,
        accepted=accepted,
        corner_rmse=rmse,
        tx=tx,
        ty=ty,
        estimated_scale=est_scale,
        estimated_angle_deg=est_angle,
        icraft_opt_s=opt_s,
        icraft_sar_s=sar_s,
        total_s=time.perf_counter() - total_start,
        matrix=matrix,
        inlier_mask=inliers,
        opt_pts=opt_pts,
        sar_pts=sar_pts,
        opt_img=opt,
        sar_img=sar,
        draw_path=draw_path,
    )
    if not args.no_images:
        draw_match_image(result, gt_aug_to_opt, Path(draw_path), args.max_draw)
    return result


def draw_match_image(result: MatchResult, gt_aug_to_opt: np.ndarray, out_path: Path, max_draw: int) -> None:
    opt_vis = cv2.cvtColor(result.opt_img, cv2.COLOR_GRAY2BGR)
    sar_vis = cv2.cvtColor(result.sar_img, cv2.COLOR_GRAY2BGR)
    gap = 24
    height = max(opt_vis.shape[0], sar_vis.shape[0])
    width = opt_vis.shape[1] + gap + sar_vis.shape[1]
    canvas = np.full((height, width, 3), 245, dtype=np.uint8)
    canvas[: opt_vis.shape[0], : opt_vis.shape[1]] = opt_vis
    canvas[: sar_vis.shape[0], opt_vis.shape[1] + gap :] = sar_vis

    mask = np.zeros((len(result.sar_pts),), dtype=bool)
    if result.inlier_mask is not None:
        mask = result.inlier_mask.reshape(-1).astype(bool)

    order = np.argsort(mask.astype(np.int32))
    if len(order) > max_draw:
        outlier_idx = order[~mask[order]][: max_draw // 2]
        inlier_idx = order[mask[order]][: max_draw - len(outlier_idx)]
        order = np.concatenate([outlier_idx, inlier_idx])

    x_offset = opt_vis.shape[1] + gap
    for idx in order:
        pt_opt = tuple(np.round(result.opt_pts[idx]).astype(int))
        pt_sar = tuple(np.round(result.sar_pts[idx] + np.array([x_offset, 0])).astype(int))
        color = (0, 220, 0) if mask[idx] else (0, 0, 255)
        cv2.line(canvas, pt_opt, pt_sar, color, 1, cv2.LINE_AA)
        cv2.circle(canvas, pt_opt, 2, color, -1, cv2.LINE_AA)
        cv2.circle(canvas, pt_sar, 2, color, -1, cv2.LINE_AA)

    sar_corners = np.array(
        [[0, 0], [result.sar_img.shape[1] - 1, 0], [result.sar_img.shape[1] - 1, result.sar_img.shape[0] - 1], [0, result.sar_img.shape[0] - 1]],
        dtype=np.float64,
    )
    gt_poly = np.round(transform_points(sar_corners, gt_aug_to_opt)).astype(np.int32)
    cv2.polylines(canvas, [gt_poly], True, (255, 180, 0), 2, cv2.LINE_AA)
    if result.matrix is not None:
        pred_poly = np.round(transform_points(sar_corners, result.matrix)).astype(np.int32)
        cv2.polylines(canvas, [pred_poly], True, (0, 255, 255), 2, cv2.LINE_AA)

    title = (
        f"ICRAFT soft-sim id={result.image_id} matches={result.matches} "
        f"inliers={result.inliers} ratio={result.inlier_ratio:.3f} "
        f"rmse={result.corner_rmse:.2f}px accepted={int(result.accepted)}"
    )
    cv2.putText(canvas, title, (12, 26), cv2.FONT_HERSHEY_SIMPLEX, 0.65, (0, 0, 0), 2, cv2.LINE_AA)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(out_path), canvas)


def result_to_row(result: MatchResult) -> dict[str, object]:
    return {
        "image_id": result.image_id,
        "stage": result.stage,
        "angle_deg": result.angle_deg,
        "synthetic_scale": result.synthetic_scale,
        "matches": result.matches,
        "inliers": result.inliers,
        "inlier_ratio": result.inlier_ratio,
        "accepted": int(result.accepted),
        "corner_rmse": result.corner_rmse,
        "tx": result.tx,
        "ty": result.ty,
        "estimated_scale": result.estimated_scale,
        "estimated_angle_deg": result.estimated_angle_deg,
        "icraft_opt_s": result.icraft_opt_s,
        "icraft_sar_s": result.icraft_sar_s,
        "total_s": result.total_s,
        "draw_path": result.draw_path,
    }


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    fieldnames = [
        "image_id",
        "stage",
        "angle_deg",
        "synthetic_scale",
        "matches",
        "inliers",
        "inlier_ratio",
        "accepted",
        "corner_rmse",
        "tx",
        "ty",
        "estimated_scale",
        "estimated_angle_deg",
        "icraft_opt_s",
        "icraft_sar_s",
        "total_s",
        "draw_path",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def print_summary(rows: list[dict[str, object]]) -> None:
    rmse = np.array([float(row["corner_rmse"]) for row in rows if not math.isnan(float(row["corner_rmse"]))])
    if len(rmse) == 0:
        print(f"Summary: cases={len(rows)}, valid=0")
        return
    print(
        "Summary: "
        f"cases={len(rows)}, valid={len(rmse)}, "
        f"<=5px={(rmse <= 5).sum()}, <=10px={(rmse <= 10).sum()}, "
        f"median={np.median(rmse):.2f}px, mean={np.mean(rmse):.2f}px"
    )
    accepted_rmse = np.array(
        [float(row["corner_rmse"]) for row in rows if int(row["accepted"]) == 1 and not math.isnan(float(row["corner_rmse"]))]
    )
    if len(accepted_rmse):
        print(
            "Accepted: "
            f"cases={len(accepted_rmse)}, <=5px={(accepted_rmse <= 5).sum()}, "
            f"<=10px={(accepted_rmse <= 10).sum()}, "
            f"median={np.median(accepted_rmse):.2f}px, mean={np.mean(accepted_rmse):.2f}px"
        )
    else:
        print("Accepted: cases=0")


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    labels = resolve_labels(args)
    angles = parse_float_list(args.angles)
    scales = parse_float_list(args.scales)
    xfeat = IcraftSoftXFeat(args)

    rows: list[dict[str, object]] = []
    for label in labels:
        for angle in angles:
            for scale in scales:
                result = run_one_case(label, angle, scale, xfeat, args)
                rows.append(result_to_row(result))
                print(
                    f"{label.image_id} angle={angle:g} scale={scale:g}: "
                    f"matches={result.matches}, inliers={result.inliers}, "
                    f"rmse={result.corner_rmse:.2f}px, "
                    f"icraft_opt={result.icraft_opt_s:.3f}s, icraft_sar={result.icraft_sar_s:.3f}s"
                )

    csv_path = args.output_dir / "xfeat_icraft_soft_sim_summary.csv"
    write_csv(csv_path, rows)
    print("")
    print(f"CSV: {csv_path}")
    print_summary(rows)


if __name__ == "__main__":
    main()
